all: game

game: game.c
	gcc -Wall -Werror -g game.c -o game

clean:
	rm -rf *.o*
	rm game

# all: game

# map.o: map.c
# 	gcc -Wall -Werror -c map.c

# linked_list.o: linked_list.c 
# 	gcc -Wall -Werror -c linked_list.c

# game: linked_list.o map.o
# 	gcc -Wall -Werror -o game game.c linked_list.o map.o 

